colegio/colegio/urls.py
from django.contrib import admin
from django.urls import path
#lo que hice fue importar todas las views de la app comunicados y se importan dos views
from comunicados.views import home, filtrar_comunicados

#se configuran las urls de home y de filtrar comunicados
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name = "home"),
    path('filtrar_comunicados/',filtrar_comunicados, name= "filtrar_comunicados")

]

colegio/comunicados/models.py
from django.db import models
#importo el moderlo user para poder usarlo como variable en el modelo comunicado
from django.contrib.auth.models import User

#modelo.categoria segun en el pdf
class Categoria(models.Model):
    nombre = models.TextField()
    descripcion = models.TextField()
    
    
    def __str__(self):
        return self.nombre


#modelo.comunicado segun en el pdf


class Comunicado(models.Model):
    #creo los niveles para poder usarlos como variables
    NIVEL_CHOICES =[  
        ("GEN","General"),
        ("PRE","Ciclo Preescolar"),
        ("BAS","Ciclo Basico"),
        ("MED","Ciclo Medio"),
    ]
    
    correlativo = models.AutoField(primary_key = True)
    titulo = models.CharField(max_length = 50)
    detalle = models.CharField(max_length = 100)
    nivel = models.CharField(max_length = 10, choices = NIVEL_CHOICES)
    categoria = models.ForeignKey('Categoria',on_delete = models.CASCADE )
    fecha_envio = models.DateTimeField(auto_now_add = True)
    fecha_ultima_modificacion = models.DateTimeField(auto_now = True)
    publicado_por = models.ForeignKey(User,on_delete = models.CASCADE)
    

    def __str__(self):
        return self.titulo
    

colegio/comunicados/views.py
from django.shortcuts import render
#importe todos los modelos creados de comunicado y categoria
from .models import Comunicado, Categoria
# Create your views here.


#Funcion home encargada de ordenar por ultima fecha de modificacion y renderisar home.html
def home(request):
    comunicados = Comunicado.objects.order_by('-fecha_ultima_modificacion')

    context ={'comunicados':comunicados}

    return render(request, "comunicados/home.html",context)


#Funcion sirve para filtrar los comunicados por nivel , categoria y renderisar comunicado.hmtl 
def filtrar_comunicados(request):
    nivel = request.GET.get('nivel')
    categoria = request.GET.get('categoria')


    comunicados = Comunicado.objects.all()

    if nivel:
        comunicados = comunicados.filter(nivel=nivel)


    if categoria:
        comunicados = comunicados.filter(categoria__nombre=categoria)   


    context = {'comunicados':comunicados,
               'niveles': Comunicado.NIVEL_CHOICES,
               'categorias': Categoria.objects.all()
               }

    return render(request, "comunicados/comunicado.html",context)

colegio/comunicados/templates/comunicados/comunicado.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>

    <title>Document</title>
</head>
<body>
    {% include 'comunicados/menu.html'%}
    <form action="{% url 'filtrar_comunicados' %}" method="GET" class="form-inline">
        <div class="d-flex">
            <label for="nivel"><h5>Nivel: </h5></label>
            <select class="form-select form-select-lg mb-3" aria-label=".form-select-lg example" name="nivel">

                {% for nivel in niveles %}
                    <option value="{{ nivel.0 }}">{{ nivel.1 }}</option>
                {% endfor %}
              </select>
      
            <label for="categoria"><h5>Categoría: </h5></label>
            <select class="form-select form-select-lg mb-3" aria-label=".form-select-lg example" name="categoría">
                <option value="">Todas</option>
                {% for categoria in categorias %}
                    <option value="{{ categoria.nombre }}">{{ categoria.nombre }}</option>
                {% endfor %}
            </select>
        <button type="submit" class="btn btn-primary">Filtrar</button>
        </div>
    </form>
    
    <section style="background-color: #86a7c7;">
        {% for comunicado in comunicados %}
        <div class="container my-5 py-5 mb-0 mt-0" >
          <div class="row d-flex justify-content-center">
            <div class="col-md-12 col-lg-10">
              <div class="card text-dark">
                <div class="card-body p-4">
                  <h4 class="mb-0">{{ comunicado.titulo }}</h4>
                  <p class="fw-light mb-4 pb-2">{{ comunicado.get_nivel_display }}</p>

                  <div class="d-flex flex-start">
                    <img class="rounded-circle shadow-1-strong me-3"
                      src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(23).webp" alt="avatar" width="60"
                      height="60" />
                    <div>
                      <h6 class="fw-bold mb-1">{{ comunicado.publicado_por }}</h6>
                      <div class="d-flex align-items-center mb-3">
                        <p class="mb-0">
                        {{comunicado.fecha_ultima_modificacion}}
                          <span class="badge bg-primary"></span>
                        </p>
                        <a href="#!" class="link-muted"><i class="fas fa-pencil-alt ms-2"></i></a>
                        <a href="#!" class="link-muted"><i class="fas fa-redo-alt ms-2"></i></a>
                        <a href="#!" class="link-muted"><i class="fas fa-heart ms-2"></i></a>
                      </div>
                      <p class="mb-0">
                        {{comunicado.detalle}}
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% empty %}
        <p>No se encontraron comunicados.</p>
        {% endfor %}
      </section>
</body>
</html>

colegio/comunicados/templates/comunicados/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Colegio Scuola Italiana Villa Alemana</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</head>
<body>
    {% include 'comunicados/menu.html'%}
    <section style="background-color: #86a7c7;">
        {% for comunicado in comunicados %}
        <div class="container my-5 py-5 mb-0 mt-0" >
          <div class="row d-flex justify-content-center">
            <div class="col-md-12 col-lg-10">
              <div class="card text-dark">
                <div class="card-body p-4">
                  <h4 class="mb-0">{{ comunicado.titulo }}</h4>
                  <p class="fw-light mb-4 pb-2">{{ comunicado.get_nivel_display }}</p>

                  <div class="d-flex flex-start">
                    <img class="rounded-circle shadow-1-strong me-3"
                      src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(23).webp" alt="avatar" width="60"
                      height="60" />
                    <div>
                      <h6 class="fw-bold mb-1">{{ comunicado.publicado_por }}</h6>
                      <div class="d-flex align-items-center mb-3">
                        <p class="mb-0">
                        {{comunicado.fecha_ultima_modificacion}}
                          <span class="badge bg-primary"></span>
                        </p>
                        <a href="#!" class="link-muted"><i class="fas fa-pencil-alt ms-2"></i></a>
                        <a href="#!" class="link-muted"><i class="fas fa-redo-alt ms-2"></i></a>
                        <a href="#!" class="link-muted"><i class="fas fa-heart ms-2"></i></a>
                      </div>
                      <p class="mb-0">
                        {{comunicado.detalle}}
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </section>

</body>
</html>

colegio/comunicados/templates/comunicados/menu.html
<nav class="navbar navbar-expand-lg" style="background-color: #009246;">
  <div class="container-fluid">
    <a class="navbar-brand" href="#" style="color:red;">Scuola Italiana</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="http://127.0.0.1:8000/" style="color: #fff;">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="http://127.0.0.1:8000/filtrar_comunicados/" style="color: #fff;">Comunicados</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <a href="http://127.0.0.1:8000/admin/" class="btn btn-primary">Ingresar</a>
      </form>
    </div>
  </div>
</nav>